version: '2'
services:
  web:
    container_name: odoo
    image: odoo:latest
    depends_on:
      - db
      - wdb
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
#      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./oca-addons:/mnt/oca-addons
    environment:
      - ODOO_LOGFILE=$LOGFILE
    command:
      - odoo
      - --workers=0
      # XXX Odoo v8 has no `--dev` mode; Odoo v9 has no parameters
      - --dev=reload,qweb,werkzeug,xml,wdb

  db:
    container_name: postgres
    image: postgres:9.4
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=trash
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

# DOC: https://github.com/Kozea/wdb
  wdb:
    container_name: wdb
    image: yajo/wdb-server
    ports:
        - "1984:1984"
volumes:
  odoo-web-data:
  odoo-db-data:
